### PR TITLE
Improve, normalise mathjax handling, yapf the file

### LINKED ISSUE #544: Same bug as notebook/#759 regarding correctly delimiting mathjax
This needs a solution similar to https://github.com/jupyter/notebook/pull/2220.

### PR DESCRIPTION
**Pull request by mpacer**
Closes #544.

### CODE REVIEW

**Comment by mpacer** [comment]
Does anyone have any issues with this PR? Or can I merge?

**Comment by takluyver** [comment]
For the future, I'd suggest keeping functional changes separate from code formatting, because it's harder to review changes to the code if they're mixed with changes to the style. As this is already here, though, go for it.

(We've also mostly discouraged large formatting changes, because the changes make things like git blame less useful. But as you're doing most of the work on nbconvert at the moment, I think you get to decide things like that)

**Comment by bollwyvl** [comment]
@mpacer will take a look at this!

**Comment by mpacer** [comment]
This is not likely to be problematic. It just aims to match the notebook in terms of its functionality; but always happy to have more review.

**Pull request merged**
