### PR TITLE
capture latex stderr

### PR DESCRIPTION
**Pull request by minrk**
allows forwarding latex errors to users (e.g. notebook save-as PDF)

closes jupyter/notebook#715

### CODE REVIEW

**Comment by takluyver** [comment]
Does it make sense to try to do anything to try to cut down the Latex output to the relevant part? I suspect the answer is that no, any part of the output may be informative, though I know Latex output tends to be extremely verbose.

What about an accompanying UI change in the notebook so that the starting view shows the last lines of the error message, as the terminal does, since this is most likely to indicate what the problem is?

**Comment by minrk** [comment]
I wouldn't know how to trim down latex output to what's relevant. Do you just mean to scroll to the bottom of the error page by default?

**Comment by takluyver** [comment]
Yep, or rather display the output in its own scrolling box which is scrolled to the bottom by default, rather than scrolling the whole page down.

**Comment by minrk** [comment]
Makes sense. Done in jupyter/notebook#1064

**Comment by takluyver** [comment]
:+1: I'll give others a chance to look at this, but it looks fine to me.

**Comment by Carreau** [comment]
Awesome !

**Pull request merged**
