### PR TITLE
WIP - Validate generated HTML

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Verifying that html generated by nbconvert templates is valid.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
html5validator is not great. It is really only a CLI tool with no clean programmatic interface, and depends on a java thing.

**Comment by MSeal** [comment]
That's too bad. I agree that doesn't like like a good dependency to add.

**Comment by SylvainCorlay** [comment]
Yeah we use it in the voila-gridstack nbconvert template and caught some errors. We may be able to do something with a pure python solution.

**Comment by SylvainCorlay** [comment]
We can apparently invoke the validator at http://validator.w3.org/ as per the stackoverflow answer here: https://stackoverflow.com/a/10519634/2502544

https://pypi.org/project/py_w3c/

**Comment by MSeal** [comment]
I'd be quite hesitant to ship local html to a service in a library call here. Especially if someone has anything sensitive as we'd be airing to the whole internet at that point without the user knowing. Plus it reduces reliable execution substantially.

**Comment by SylvainCorlay** [comment]
> I'd be quite hesitant to ship local html to a service in a library call here. Especially if someone has anything sensitive as we'd be airing to the whole internet at that point without the user knowing. Plus it reduces reliable execution substantially.

I totally agree, that we cannot rely on a service. Just pointing at the existing solutions to see if there is something better we can do about it.

**Comment by SylvainCorlay** [comment]
Closing as I don't think we have a good solution for that yet.

**Pull request closed without merging**
