### PR TITLE
Run tests on GitHub actions

### LINKED ISSUE #1615: Since we are out of travis builds, we should probably move to GitHub actions
Currently, travis CI does not run.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #1615.

### CODE REVIEW

**Comment by jasongrout** [comment]
Sorry, I didn't see this until after I started working on it as well over at #1617. I have tests "passing" (but skips a number of tests apparently, maybe because I skip installing a bunch of packages?).

**Comment by RAJSINGH-Bitian** [comment]
@SylvainCorlay hey i'm new to jupyter i want to work in your guidance . i will you please guide me to how to work in jupyter community.i will be very greatful to you.

**Comment by jasongrout** [comment]
> maybe the skips are because I skip installing a bunch of packages

Turns out that is the case. Over in #1617, we now have all 291 tests passing now.

**Comment by jasongrout** [comment]
@RAJSINGH-Bitian - I'd suggest picking a project, reading the documentation or looking for "good first issues", and going from there.

**Comment by jasongrout** [comment]
Superseded by #1617

**Pull request closed without merging**
