### PR TITLE
Add CLI configuration for disable-chromium-sandbox

### PR DESCRIPTION
**Pull request by skovhus**
This add CLI configuration parameter for the feature introduced in https://github.com/jupyter/nbconvert/pull/1516

Closes https://github.com/jupyter/nbconvert/issues/1490

### CODE REVIEW

**Comment by MSeal** [comment]
I think you'll still need to pass that trailer assignment to the pyppeteer call as well

**Comment by skovhus** [comment]
> I think you'll still need to pass that trailer assignment to the pyppeteer call as well

I'm not sure I follow, can you elaborate? I tested this out and the new CLI flag is being forwarded correctly.

**Comment by MSeal** [comment]
Ahh nvm the traitlet within the class was already set that you're setting at the app level. Thanks for testing that it's working!

**Comment by MSeal** [comment]
Test failures are related to changing test patterns over from circleci and we can ignore those for this PR

**Pull request merged**
