### PR TITLE
Release 5.4

### LINKED ISSUE #647: Next release?
I'm trying to add Jupyter to Homebrew, a package manager for macOS (see Homebrew/homebrew-core#16718). One of Homebrew's policies is that, whenever possible, the default macOS install of Python (2.7.10 on my box) is used.

It looks like `jupyter-nbconvert` is failing in their test infrastructure due to a UTF-8 issue fixed in 77d4956ddd252f5d1c05f440acd5b53bd9d996c4. I was wondering when we can expect the next release of Nbconvert to hopefully get this fix into a release 🙂

### LINKED ISSUE #861: make a new release？
It’s been a year since the last release.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #861

### CODE REVIEW

**Comment by blink1073** [comment]
@minrk, good to go?

**Comment by MSeal** [comment]
We hopefully can get into faster cadence for this moving forward. I'll try to get a few small items pushed for a later release (not close enough to ready for this one)

**Comment by Carreau** [comment]
setup.py does not seem to have the `python_requires` metadata.

**Comment by Carreau** [comment]
Any objection to give @MSeal push right on PyPI/conda-forge ?

**Comment by blink1073** [comment]
No objections from me!

**Comment by blink1073** [comment]
I'm afk, so couldn't make the python_requires change until later.

**Comment by Carreau** [comment]
> I'm afk, so couldn't make the python_requires change until later.

See #871

**Comment by Carreau** [comment]
In which I also add the question of whether we want to drop 2.7....

**Comment by MSeal** [comment]
Maybe with the major release so we can keep hotfix paths open in an organized manner? I think there's a lot of python 2 users still based on issues / conversations I've seen passed through papermill

**Comment by Carreau** [comment]
> Maybe with the major release so we can keep hotfix paths open in an organized manner

Seem like a good plan. Hopefully with the python_requires python 2 users should still get a version of nbconvert that works on their machine. We also need to keep in mind that kernels can still by python 2 as well.

**Comment by blink1073** [comment]
Ready to roll. Happy to release tomorrow or defer to @MSeal.

**Comment by MSeal** [comment]
Either way -- though I'm not on the maintainers list yet.
I'm assuming the project releases without any fancy setup calls (contributing.md doesn't specify if anything beyond bdist + sdist + twine is needed).

**Comment by Carreau** [comment]
It's always a good thing to have Someone new going through the release to see if documentation is imprecise/missing :-P

**Comment by mpacer** [comment]
@MSeal I can be around tomorrow online to help work through these steps. Agreed with @Carreau that it's always good to have someone new going through the release process. 

I'm going to give MSeal rights on pyPI since it sounds like everyone else was on board with that.

**Comment by MSeal** [comment]
Ahh good point -- I can make that change.

Had to have M help with https://github.com/jupyter/nbconvert/pull/872 so I didn't get to pair on releasing today

**Comment by MSeal** [comment]
I need to add the description and long_description, was going to tackle it tomorrow (today is a holiday here) and see if M is around to pair on releasing.

**Comment by MSeal** [comment]
We're putting together the changelogs -- adding some documentation notes for the next new person to run through this process.

**Comment by blink1073** [comment]
This PR includes change logs

**Comment by MSeal** [comment]
There are some late additions missing

**Comment by blink1073** [comment]
Ah, just making sure you didn't go through the same pain I already did. 😉

**Comment by Carreau** [comment]
Apparently setuptools and PyPI do support
```
project_urls={
            "Bug Tracker": "https://bugs.example.com/HelloWorld/",
            "Documentation": "https://docs.example.com/HelloWorld/",
            "Source Code": "https://code.example.com/HelloWorld/",
        }
```

`https://github.com/pypa/warehouse/issues/1419`, `https://github.com/pypa/setuptools/pull/1210`

**Comment by Carreau** [comment]
I pushed a short-ish long description plus a couple of other things. 
Please see the latest additions.

**Comment by SylvainCorlay** [comment]
I don't see @Carreau 's commit in the git history. Was there a history rewrite?

**Comment by SylvainCorlay** [comment]
The test failure comes from `long_description` having been added to the master branch as well.

@blink1073 @Carreau would you like to fix this? I am eager to get this in...

**Comment by Carreau** [comment]
Feel free to push a commit removing long description. Thanks for looking
into this I was baffeled. Currently In a car so won't do it before a couple
of hours.

**Comment by blink1073** [comment]
I also won't be able to get back to this until later today.

**Comment by SylvainCorlay** [comment]
Are you fine with me merging and fixing in master?

**Comment by SylvainCorlay** [comment]
OK, going ahead with it :)

**Comment by SylvainCorlay** [comment]
Leaving it to M to tag 5.4!

**Comment by mpacer** [comment]
Matt and I will take another attempt at getting this out today. We got really far for the amount of time we had to work on it yesterday. Now, it’s mostly crafting the notes about the major user-facing feature and convention changes so we can send out the announcement email.

**Comment by mpacer** [comment]
In the future I’d prefer not to merge changes that break our tests on master, regardless of how urgently any of us want a feature to be released.

**Comment by SylvainCorlay** [comment]
> Matt and I will take another attempt at getting this out today. We got really far for the amount of time we had to work on it yesterday. Now, it’s mostly crafting the notes about the major user-facing feature and convention changes so we can send out the announcement email.

Thanks! Looking forward to it.

> In the future I’d prefer not to merge changes that break our tests on master, regardless of how urgently any of us want a feature to be released.

I get it, although the required change was trivial, tested locally, and allowed us not to wait for the original PR author to rebase his PR, as he was not available.

**Comment by mpacer** [comment]
@SylvainCorlay You could have pushed onto this PR rather than pushing onto master. _That_ I would have been totally ok with :).

That's the beauty of the allow edits from maintainers option from github!

**Comment by SylvainCorlay** [comment]
Yeah I wanted to do that, but the build error came from `merging` the branch into master where the same extra argument had already been added at a different line.

**Pull request merged**
