### PR TITLE
fallback on PycURL for insecure versions of Python

### LINKED ISSUE #24: Can't install nbconvert in python 2.7.6
It's impossible to install `nbconvert` in ubuntu 14.04 with python 2.7 since this [commit](https://github.com/jupyter/nbconvert/commit/c14a5bbde0d380518611392a67b08538f76dcb04). There is a bug in urlib <http://bugs.python.org/issue11220> urllib send SSLv23 protocol and the jupyter cdn server only accepts SSLv3.

### PR DESCRIPTION
**Pull request by minrk**
When downloading CSS from secure CDN, SSL validation may fail for old or insecure versions of Python. In those cases, try again with pycurl if available.

Example output without PycURL:

```
$ /usr/bin/python setup.py css
running css
Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
Failed, try again after installing PycURL with `pip install pycurl` to avoid outdated SSL.
Failed to download css from https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css: [Errno socket error] [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

With PycURL:

```
running css
Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
Failed, trying again with PycURL to avoid outdated SSL.
Downloaded Notebook CSS to nbconvert/resources/style.min.css
```

closes #24

### CODE REVIEW

**Comment by rgbkrk** [comment]
Well I'm certainly a fan of this, even if it is for CSS.

**Comment by Carreau** [comment]
+1

**Comment by xvrdm** [comment]
Could you please let me know if this was fixed?

I am seeing the issue while trying to install with current version of Jupyter.

System: Centos 6.6
Node: 0.12.7

Current pip freeze (confirming that pycurl is actually installed):

```
...
pickleshare==0.5
pyasn1==0.1.7
pycparser==2.12
pycurl==7.19.5.1
Pygments==2.0.2
pyOpenSSL==0.15.1
...
```

and error when running `pip install -r requirements.txt -e .`

```
...
  Running setup.py develop for ipython
  Running setup.py develop for ipykernel
  Running setup.py develop for nbconvert
    Complete output from command /home/xadam/notebooks/DOCTORPY/bin/python2.7 -c "import setuptools, tokenize; __file__='/home/xadam/notebooks/DOCTORPY/src/nbconvert/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    /home/xadam/notebooks/DOCTORPY/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '4.0.0.dev' to '4.0.0.dev0'
      normalized_version,
    running develop
    running css
    Failed, try again after installing PycURL with `pip install pycurl` to avoid outdated SSL.
    Failed to download css from https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css: [Errno socket error] [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
    Downloading CSS: https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css
    error: Need Notebook CSS to proceed: nbconvert/resources/style.min.css

    ----------------------------------------
Command "/home/xadam/notebooks/DOCTORPY/bin/python2.7 -c "import setuptools, tokenize; __file__='/home/xadam/notebooks/DOCTORPY/src/nbconvert/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/xadam/notebooks/DOCTORPY/src/nbconvert
```

Weirdly enough, `python setup.py css` run without problem and install all the bower dependencies. But that does not solve the issue with `nbconvert`.

**Comment by minrk** [comment]
@xvrdm from your error message:

> try again after installing PycURL with `pip install pycurl` to avoid outdated SSL.

Can you try that?

**Comment by xvrdm** [comment]
Yes but it's already installed:

```
$ pip install pycurl
Requirement already satisfied (use --upgrade to upgrade): pycurl in /home/xadam/notebooks/DOCTORPY/lib/python2.7/site-packages

$ pip install --upgrade pycurl
Requirement already up-to-date: pycurl in /home/xadam/notebooks/DOCTORPY/lib/python2.7/site-packages
```

**Pull request merged**
