### PR TITLE
Add enable_async trait for Jinja async template execution

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Needed for Voila to have an asynchronous execution model, but could be useful in general.

**Comment by davidbrochart** [comment]
@MSeal do you think it can be merged? This is necessary for Voila to be able to use nbclient's async execution.

**Comment by davidbrochart** [comment]
ping @MSeal

**Comment by davidbrochart** [comment]
ping @SylvainCorlay

**Comment by MSeal** [comment]
Sorry for missing this earlier -- been a little behind all the threads I'm pinged on.

**Comment by SylvainCorlay** [comment]
Thanks @davidbrochart !

**Comment by davidbrochart** [comment]
Thank you!

**Pull request merged**
