### PR TITLE
fix issue #463

### LINKED ISSUE #463: Fatal error occurred: #1->\CYREREV
[test(ipynb).txt](https://github.com/jupyter/nbconvert/files/586568/test.ipynb.txt)

After the execution of command: `jupyter nbconvert test.ipynb --to latex test.ipynb` I received this file [test(tex).txt](https://github.com/jupyter/nbconvert/files/586512/test.tex.txt).

And only then I use `pdflatex test.tex` to get test.pdf.
But before that I need to replace `\usepackage[T1]{fontenc}` with `\usepackage[T2A]{fontenc}` to avoid problem with cyrillic (russian) characters.

When I tried to execute `jupyter nbconvert test.ipynb --to pdf` I got this:
> ~/Desktop$ jupyter nbconvert test.ipynb --to pdf
[NbConvertApp] Converting notebook test.ipynb to pdf
[NbConvertApp] Writing 14914 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2016/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: 'fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/url/url.sty))
Package hyperref Message: Driver (autodetected): hpdftex.
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/local/texlive/2016/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/ltcaption.sty)
>*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/umsb.fd)
LaTeX Warning: No \author given.
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1pcr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/data/uni-4.def)
! Undefined control sequence.
\u-default-1069 #1->\CYREREV 
                             
>l.279 ...h{} Это русский коммент}
                                                  
>? 
! Emergency stop.
\u-default-1069 #1->\CYREREV 
                             
>l.279 ...h{} Это русский коммент}
                                                  
>!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Also when I tried to save my ipython notebook as PDF: File -> Download as -> PDF via LaTeX (.pdf), I received this Internal Server Error:
screen shot 2016-11-11 at 22 07 13

Today I found out the solution of this issues:
1. replace `\usepackage[T1]{fontenc}` with `\usepackage[T2A]{fontenc}` in the nbconvert/templates/latex/base.tplx
2. small changes in file nbconvert/nbconvert/exporters/pdf.py

### PR DESCRIPTION
**Pull request by Akarazeev**
Now “File -> Download as -> PDF via LaTeX (.pdf)” works well even if
jupyter notebook contains russian characters

### CODE REVIEW

**Comment by takluyver** [comment]
(Please hold off merging this until we've understood the issue better - see #463 )

**Comment by michaelpacer** [comment]
I'm closing this for a couple reasons. 

Master does not have the failure mentioned in #463. It also may not display the characters appropriately based on a default LaTeX font setup. 

If we want to genuinely support pdfs with cyrillic characters, changing the character set package (T1 → T2A) won't be enough on a default configuration. Also T2A, on its own, has some issues with latin combining characters (e.g., ü). So to support it, we would need to guide people on how to install & link to the appropriate fonts. This doesn't cover this kind of documentation (especially across multiple platforms). 

If were to cover this, we would need to test it as well. If you wanted to create a separate PR that would test for not failing when cyrillic characters are included (the original concern in #463), that would be a good first step to get this support.

That aside, I don't understand the change made to the bibtex invocation. Our bibtex call is not a fall-through mechanism like this PR seems to make it. You usually need multiple invocations of LaTeX in order to link the bibliography appropriately to the rest of the document. I imagine that's the source of the current structure in general, but I don't get why the multiple calls sit underneath _separate_ conditionals.

**Comment by takluyver** [comment]
> I imagine that's the source of the current structure in general, but I don't get why the multiple calls sit underneath separate conditionals.

I think the idea is that if the first call to latex fails, we should fail without trying to do each subsequent step. It's a bit confusing because normally the return code from a process is 0 for success, but our `run_command()` function switches it round with `True` for success and `False` for failure.

**Comment by Akarazeev** [comment]
> If we want to genuinely support pdfs with cyrillic characters, changing the character set package (T1 → T2A) won't be enough on a default configuration. Also T2A, on its own, has some issues with latin combining characters (e.g., ü).

For me T2A works well even with ü.

screen shot 2016-11-12 at 11 08 55
screen shot 2016-11-12 at 11 09 04

**Comment by michaelpacer** [comment]
I have some issues with the placement of the umlaut, but I believe that that could be the actual font design, just one I happen to disagree with (they do not look appropriately aligned). Nonetheless, I had originally meant to link to where I had gotten that info from this stackexchange answer: http://tex.stackexchange.com/questions/148050/why-to-use-t2a-t1-when-t2a-is-enough

My guess is that there are slight spacing differences, and there are certainly some changes that seem to result from this (assuming you were converting the same file in both cases only changing that argument). But that isn't what leads me to oppose including this right now. 

We need a more general plan for supporting non-Latin character sets if we are going to support it by default. This includes developing a plan for installing the fonts needed to support this across platforms. Part of what is holding us back (as discussed in the dev meetings online a few months ago, if you want I can find the link) we don't have a big enough integral over the expertise × # of free cycles to be able to support any particular non-Latin script, as it often can require expertise in using and reading in that script. If you are able to help us maintain and develop that documentation, then we can start talking about a plan for supporting cyrillic character sets by default (which, in an ideal world, we would already be doing, but in a world of finite expertise × time surfaces it's not currently possible). 

In the mean-time & even if you don't have the time/energy to help us integrate this into the main repository with ongoing support, if you make a custom exporter you can implement your solution that works on your configuration today.

**Comment by Akarazeev** [comment]
Ok, I understand. I will notify you when I have more time and be able to implement my solution.
Thank you for explanation.

**Pull request closed without merging**
