### PR TITLE
Allow specifying the widgets renderer semver range

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
YES! We needed this ages ago :)

**Comment by SylvainCorlay** [comment]
I want a better name for `jupyter_widgets_base_url`.

It is the CDN URL for third-party widgets. What about `jupyter_widgets_cdn_url`?

**Comment by maartenbreddels** [comment]
in principle it can also be a local URL, i someday hacked this for local dev. It could also just be 1 variable right?

`jupyter_widgets_script_url` ?

**Comment by SylvainCorlay** [comment]
Moving forward with this. Will include the script URL in another PR. Still not sure about the naming...

**Comment by SylvainCorlay** [comment]
Ping @jasongrout

**Pull request merged**
