### PR TITLE
Convert proxy handler from callback to coroutine

### PR DESCRIPTION
**Pull request by takluyver**
According to the tornado docs, the `web.asynchronous` decorator is deprecated in 5.1 and will be removed in 6.0. There's no direct suggested replacement; it just says to use coroutines instead.

### CODE REVIEW

**Comment by takluyver** [comment]
I'll merge this soon unless anyone wants more time to look at it (@mpacer @MSeal )

**Comment by MSeal** [comment]
Looks good. That reminds me that we need to get the patch release going as well.

**Comment by alejopijuan** [comment]
@takluyver hey Thomas, I'm still getting the 500 Internal Server Error on the jupyter notebook. Any idea of what I should do?

**Comment by takluyver** [comment]
If you're seeing the error this PR fixed, it's because you're using tornado 6.0a1 - a as in alpha. In that case, what you should do is go back to the stable version: `pip install tornado<6`. Hopefully any issues will be fixed well by the time Tornado 6 is stable.

**Pull request merged**
