### PR TITLE
Re-allow capitalised --to options

### PR DESCRIPTION
**Pull request by takluyver**
e.g. `--to HTML`

Fixes a failing test

### CODE REVIEW

**Comment by takluyver** [comment]
This was accidentally broken in #185 (by my changes, I think). We should ensure it gets into any release those changes are in.

**Comment by minrk** [comment]
Want to capitalize one of our tests to catch this in the future?

**Comment by takluyver** [comment]
There already is one - you may have seen a Jenkins failure email this morning. But it seemingly doesn't run on Travis.

**Comment by takluyver** [comment]
Added a non-pandoc test so we can catch it on Travis.

**Comment by minrk** [comment]
Gotcha. I hadn't gotten to that notification in my pile of emails from the weekend, yet.

**Pull request merged**
