### PR TITLE
Add test for linked .jpeg

### PR DESCRIPTION
**Pull request by WillEngler**
In response to #176

I added a new fixture .ipynb to tests/files along with a .jpeg that the notebook links to. I figured you'd rather have a separate file to test .jpegs rather than adding another cell to one of the existing notebooks with a .png.

I'm happy to iterate on this if you have any critiques.

### CODE REVIEW

**Comment by takluyver** [comment]
Technical matter: awwww!

**Comment by takluyver** [comment]
Real technical matter: unfortunately I don't think this test is exercising the problem fixed by #175 (which is what #176 was opened for). The problem was in the extract output preprocessor, which turns embedded data in outputs into separate files. So to test it, we need a notebook with an embedded jpeg in the output of a code cell, rather than just linked from a markdown cell.

**Comment by WillEngler** [comment]
Ahhhh. Pretty fundamental misunderstanding on my part. Thanks for setting me straight.

**Comment by WillEngler** [comment]
Double checking: _this_ is embedded output, right? If so, I'll fix up the PR and send it back. Thanks for bearing with me!

screen shot 2016-02-20 at 1 07 47 pm

**Comment by takluyver** [comment]
IIRC you need an `embed=True` parameter in there, otherwise it just links to the existing file. Check that there's a blob of base64 encoded data in the ipynb file.

**Comment by WillEngler** [comment]
(If this looks good to you, I could squash that second commit if you like)

**Comment by takluyver** [comment]
Looks good to me, thanks. I don't think there's a particular need to squash here, so if you want to fix the docstring, this can be merged.

**Comment by WillEngler** [comment]
Good catch on the docstring. Fixed!

**Comment by takluyver** [comment]
:cake:

**Pull request merged**
