### PR TITLE
Make pagination configurable in webpdf

### PR DESCRIPTION
**Pull request by yuvipanda**
- Add option to paginate PDF generated via webpdf
- Default to pagination, to be a drop-in for the LaTeX
  PDF generator as much as possible.

Ref #1464

### CODE REVIEW

**Comment by yuvipanda** [comment]
@SylvainCorlay do you remember what the driving use case for turning off pagination in https://github.com/jupyter/nbconvert/pull/1402 was?

**Comment by SylvainCorlay** [comment]
Hey @yuvipanda thanks for this!

When we did #1402, there was no release including webpdf yet, and I was having issues with pagination, so I probably decided to remove it together before the release.

**Comment by SylvainCorlay** [comment]
It does not seem you are actually defaulting to pagination (in contrary to the PR description). Although I am not sure we should default to pagination (for backward compat). What do you think?

**Comment by yuvipanda** [comment]
@SylvainCorlay ah, thanks for that catch. Made it the default now.

It looks like pagination was the default until 6.0.4, when single page became the default. IMO, it's ok to revert it in another patch release. webpdf is also such a new convertor, I think it's ok.

**Comment by SylvainCorlay** [comment]
LGTM.

The issue in the tests looks like a problem with quotes in a string.

**Comment by yuvipanda** [comment]
@SylvainCorlay yeah, that's unrelated - I've #1512 to try and fix that.

**Pull request merged**
