### PR TITLE
Revert unintended effects of #1966

### LINKED ISSUE #1970: nbconvert --to notebook --output out.ipynb filename incorrect
Outputs to a file called "out.nbconvert.ipynb" instead of "out.ipynb" as expected.

The expected behavior was the case prior to v7.3, likely related to #1967, though not super obvious how this behavior emerges, looking at the diff as an outsider to this codebase.
My guess is that it is related to stripping the extension off there.

A similar change does not seem to happen for other conversions, e.g. `md` or `pdf`

Steps to reproduce:

Any ipynb will do, I just made a new, empty, ipynb file and called it "test.ipynb"

```bash
$ ls
test.ipynb
$ jupyter nbconvert --to notebook --output out.ipynb test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 617 bytes to out.nbconvert.ipynb
```

This is currently breaking matplotlib's tests, which rely on the expected output path being valid.

### LINKED ISSUE #1979: Cannot convert equally named notebooks in different directories in-place
This command used to work before 7.3.0:

```bash
jupyter nbconvert --clear-output --inplace a/nb.ipynb b/nb.ipynb
```

but now reports the following error:

```
ValueError: Conversion would override an already generated output. This is probably due to --output or output_base configuration leading to non-unique output names. Output notebook names were: ['nb', 'nb']
```

The check that is failing was introduced in #1967. As a workaround running the command for each notebook individually works, but it would be nice if this could work as it did before.

### PR DESCRIPTION
**Pull request by tuncbkose**
Revert to the previous default filename behavior
```
$ ls
test.ipynb
$ jupyter nbconvert --to notebook --output out.ipynb test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 72 bytes to out.ipynb
$ jupyter nbconvert --to notebook test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 72 bytes to test.nbconvert.ipynb
```

Closes #1970.

Edit:
Additional things to fix:
- [x] #1979 same nb names in different directories 
  - Fixed by removing the incorrect check that was failing (and an associated test). As a result, if `output_base` doesn't include some format section (like `{notebook_name}`), some files might get overwritten. This should not happen unless the user specifically wants it.
- [x] I don't think using `{notebook_filename}` will always work the way it was intended. Even if it does, it doesn't have any tests, which I should add.
  - Just removed this functionality as it doesn't seem to work cohesively with existing `FilesWriter` configuration.

Now also closes #1979.

### CODE REVIEW

**Comment by tuncbkose** [comment]
@meeseeksdev tag bug

**Comment by tuncbkose** [comment]
Not sure if failures are related

**Comment by krassowski** [comment]
I restarted the failing CI jobs, maybe these are just flaky.

**Comment by tuncbkose** [comment]
Rebasing onto main

**Comment by tuncbkose** [comment]
Failure seems unrelated to me

**Review by blink1073 — APPROVED** [review]
Thank you!

**Pull request merged**
