### PR TITLE
Change ipython_genutils.tempdir calls to testpath.tempdir and tempfile

### PR DESCRIPTION
**Pull request by michaelpacer**
Elsewhere we speak of removing dependencies on ipython_genutils. I ran a grep and found the cases where I know we were using them needlessly, specifically related to creating temporary directories and replaced them with `testpath.tempdir` if it was a `TemporaryWorkingDirectory` and the standard library `tempfile` if it was a `TemporaryDirectory` since `testpath.tempdir` was just importing that itself anyway.

### CODE REVIEW

**Comment by michaelpacer** [comment]
oops. `tempfile` only works in this way on python3.2 and above. 

Can't wait for the python3 filled future.

Fortunately, `testpath.tempdir` should have our backs. At least this `testpath.tempdir` only version runs locally on python2 with py.test.

**Comment by takluyver** [comment]
:+1:

`testpath.tempdir` comes from a copy of `IPython.utils.tempdir` before the big split, so it should be a drop-in replacement.

**Comment by michaelpacer** [comment]
Ok, is this ready to be merged? There wasn't anything more I was going to add to this PR.

**Comment by minrk** [comment]
Only one thing missing: moving testpath to a standard requirement in setup.py. It's only a tests requirement at the moment.

**Comment by michaelpacer** [comment]
Ok. That should be covered now.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
