### PR TITLE
Escape HTML characters in latex output strings

### PR DESCRIPTION
**Pull request by eric-wieser**
Without this change, latex like `\left<content\right>` renders as a `<content\right>` html tag, which mathjax can't handle.

See https://nbviewer.jupyter.org/urls/galgebra--417.org.readthedocs.build/en/417/tutorials/algebra.ipynb#More-examples for an example of this failing.

This is like #514, but for cell outputs.

### CODE REVIEW

**Comment by eric-wieser** [comment]
CI failure look unrelated.

**Comment by eric-wieser** [comment]
Restarting CI just to be sure.

**Comment by MSeal** [comment]
CI docs build I'm going to try fixing today, don't worry about that one

**Comment by eric-wieser** [comment]
Coping the notebook is fine, but it depends on `galgebra` and `sympy`, which make no guarantees of latex ewuivalence between versions.

I guess if you don't rerun the notebook then it does not matter.

**Comment by eric-wieser** [comment]
Since I'm not really familiar with the structure of this project, would it be ok if I left the lab notebook and other HTML pages to you?

**Comment by MSeal** [comment]
Sure, I can push into the PR where else it's obvious the same change needs applying when I get a chance.

**Pull request merged**
