### PR TITLE
Replaced execute preprocessor internals with nbclient calls

### PR DESCRIPTION
**Pull request by MSeal**
Finishes https://github.com/jupyter/nbconvert/issues/821. Took me a while to get around to it, but here's the PR with all the stuff moved into nbclient deleted.

I found that given how light the wrapper is now only a few very basic tests should be present. I didn't like how I had to subprocess NBClient's class to account for all the traitlet assignment junk, but it works and leave the interface backwards compatible. If nbclient ever needs to move it's interface forward or off trailets or whatever, we can capture it here for translation against future versions.

### CODE REVIEW

**Comment by MSeal** [comment]
I think after this merges we can do 6.0.0a1 release

**Comment by choldgraf** [comment]
The amount red in this PR makes me happy

**Comment by MSeal** [comment]
Hmm need to look into the 3.5 failure -- might be related to the async wrappers since 3.5 has less support therein.

**Comment by MSeal** [comment]
Not sure why 3.5 is hanging on allow-errors -- will debug that later

**Comment by davidbrochart** [comment]
I tested this PR locally with python3.5, it seems to *randomly* hang on `test_allow_errors` (it doesn't happen with python3.6).
Asyncio was still missing some important features in 3.5, and nbclient is implemented using asyncio. We work around the limitations of 3.5 with e.g. the [async_generator](https://github.com/python-trio/async_generator) library, but there might be other things that are problematic.
Is there a plan to drop python3.5 in nbconvert, nbclient, and in the Jupyter ecosystem in general?
In Voila, switching to async means dropping python3.5 anyway, since we need async generators in Jinja, which is not going to happen in python3.5: https://github.com/pallets/jinja/issues/1058

**Comment by choldgraf** [comment]
I am +1 on deprecating 3.5 after a deprecation cycle, now that we are already nearing 3.9

**Comment by MSeal** [comment]
Yeah the general guidance I've been following is to support 3.5 until it cycles out of the supported path for python proper. The reason I've tried to keep maintaining it is there's some larger orgs whose internal default python version is still 3.5. Dropping support for it before python does would disrupt updates for those orgs. Still I think later this year 3.5 can drop. For now I'd be ok with marking those tests as 3.6+ only and putting a big warning in the release notes that 3.5 may have stability issues with this change given async support. Thoughts?

**Comment by davidbrochart** [comment]
Sounds good to me.

**Comment by MSeal** [comment]
Ok based on conversations across a few companies and in https://github.com/jupyter/nbclient/pull/34 I'm going to update this PR and drop support for Python 3.5. The async code in upstream libraries has caused issues in each repo for python 3.5.

**Comment by MSeal** [comment]
Going to merge this to get some things moving

**Pull request merged**
