### PR TITLE
Make date configurable in latex/PDF

### LINKED ISSUE #1962: Enhancement: Set LaTeX/PDF document date
Similar to the ability to setting the document's author and title, I'd like to set the date.

The document might be compiled/reproduced from the source later (e.g. as part of a [DVC pipeline](https://dvc.org/doc)), but the contents didn't change.

This can be achieved fairly easily by changing https://github.com/jupyter/nbconvert/blob/main/share/templates/latex/base.tex.j2#L182

It would be great to have the possibility to suppress the date as well. This can avoid any ambiguity or false dates.

### PR DESCRIPTION
**Pull request by achimgaedke**
That's a working example of implementing https://github.com/jupyter/nbconvert/issues/1962.

Fix #1962

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for working on this!  The changelog gets auto-generated, can you please add a note in `docs/source/usage.rst` instead?

**Comment by achimgaedke** [comment]
@blink1073 - done, also documented the other fields, `author` and `title`.

**Comment by achimgaedke** [comment]
I've added some command line options, they round the feature off nicely.

I find notebook metadata viewing/editing not very obvious, I guess this is a common fate of features becoming more important than expected.

**Review by blink1073 — APPROVED** [review]
Fantastic, thank you!

**Comment by blink1073** [comment]
I'll make a release with this on Monday.

**Pull request merged**
