### PR TITLE
Release 5.5 Notes

### PR DESCRIPTION
**Pull request by MSeal**
This has all the change notes, along with a few fixes to release instructions. Please review and I will rebase this PR until everything is ready for the release.

### CODE REVIEW

**Comment by t-makaro** [comment]
Any chance we can get #992 merged for 5.5?

**Comment by MSeal** [comment]
@t-makaro I'll give it some testing today. If it's looking solid we can probably slip it in.

**Comment by t-makaro** [comment]
I noticed a couple naming errors that are small fixes that will be needed before #938 can be nicely tackled. I've already submitted PRs for them.

**Comment by MSeal** [comment]
Ok -- I think all the fixes that will applied to 5.5 are merged and locked in now. Planning on releasing tomorrow.

**Comment by mpacer** [comment]
The quick change from #1002 should be added to the notes before merging.

**Pull request merged**
