### PR TITLE
fix ansi2latex filtering

### LINKED ISSUE #1071: Colored Text Crashes PDF Export
Printing colored text results in latex conversion when exporting to pdf that fail to process by xelatex.

Executing and then exporting via `jupyter nbconvet --to=pdf ColorExportFail`
```
from colorama import Fore, Back, Style 
print(Fore.RED + 'red')
```

Raises an exception:
```
! FancyVerb Error:
  Empty verbatim environment
.
\FV@Error ...ncyVerb Error:^^J\space \space #1^^J}
                                                  
l.381 }\end{Verbatim}
```

Just exporting the latex via `jupyter nbconvet --to=latex ColorExportFail` produces
```
    \begin{Verbatim}[commandchars=\\\{\}]
\textcolor{ansi-red}{red
}\end{Verbatim}
```

Instead of
```
    \begin{Verbatim}[commandchars=\\\{\}]
\textcolor{ansi-red}{red}
\end{Verbatim}
```
The extra newline breaks exports.

[ColorExportFail.txt](https://github.com/jupyter/nbconvert/files/3439599/ColorExportFail.txt)

This is on current master (5.5.0)

### PR DESCRIPTION
**Pull request by t-makaro**
Alternative to #1073. Fixes #1071

This produces:
image

As opposed to what #1073 produces:
image

@MSeal I'll leave it to you to decide which option to choose.

### CODE REVIEW

**Comment by mgeier** [comment]
FWIW, I've solved this problem in `nbsphinx` by stripping `'\n'` from the end of all `stream` outputs:

https://github.com/spatialaudio/nbsphinx/blob/f09f4490525300d5c45213aab3d50d4da68ec40a/src/nbsphinx.py#L1247-L1250

I assume this would still need #1073 (which is a good idea anyway).

I think there is no perfect solution though, because the Jupyter notebook format has some inconsistencies regarding trailing `'\n'`.

**Comment by njapke** [comment]
The results here look much nicer than mine in #1073, but I feel like trimming all trailing `\n` might be a better solution. The verbatim environment should be produced correctly without needing to trim whitespace in the templates.

**Comment by t-makaro** [comment]
Alright, I adjusted to just remove that whitespace. I agree this is a cleaner solution, and it does appear to render as expected with my test pdfs.

**Comment by mgeier** [comment]
@t-makaro When you think about it, it doesn't really make sense to add this functionality to a function named `ansi2latex()`. I think the `'\n'` should be removed before passing the string to `ansi2latex()`.

> I could create a separate filter for removing this newline and only apply it too the stream block.

Yes, this sounds more reasonable.

This will not change the result, but I think in the long run it is better to have functions that do what their name suggests and not arbitrary other things on top of that.

**Comment by t-makaro** [comment]
Now implemented using a filter called: ```strip_trailing_newline```.

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nbconvert-5-6-0-release/1867/1

**Pull request merged**
