### PR TITLE
Add ExtractAttachmentsPreprocessor

### PR DESCRIPTION
**Pull request by tuncbkose**
Adds a new preprocessor to extract notebook attachments into individual files, so that conversion outputs (like `.md/.tex` files) work properly.

Fixes https://github.com/jupyter/nbconvert/issues/1977.

Todos

- [x] Finish implementation
- [x] Finish preprocessor tests
- [x] Add tests related to FilesWriter tweaks

### CODE REVIEW

**Comment by tuncbkose** [comment]
The previous iteration was fine with the tests, but it looks like the way I associated attachment directories with specific notebooks broke something. Will look into it soon.

**Comment by tuncbkose** [comment]
I am not sure what is the best way to enable this preprocessor. I initially thought of adding it to `TemplateExporter.default_config` but ran into #1980.

For now, I enabled it for markdown and latex exporters.

**Comment by tuncbkose** [comment]
It might be worth noting that I am aware `ExtractOutput` is pretty similar, but I am under the impression that cell outputs and attachments are different enough mechanisms to warrant different preprocessors. Still, they should probably work relatively similarly, for example if a directory is created to save related files.

I'll take a look to see how it works and make appropriate changes later.

**Comment by tuncbkose** [comment]
Updated with latest commits to main

**Review by blink1073 — APPROVED** [review]
Thank you!

**Pull request merged**
