### PR TITLE
Bump version number to 5.0

### PR DESCRIPTION
**Pull request by takluyver**
Branch 4.x from the commit before the merge of this.

### CODE REVIEW

**Comment by minrk** [comment]
Have we already merged breaking changes?

**Comment by Carreau** [comment]
> Have we already merged breaking changes?

As far as I can tell, no , we did our best to actually keep API.

**Comment by takluyver** [comment]
OK, this is deferred indefinitely until there are some breaking changes. Closing so it doesn't clutter up the PR list.

**Comment by minrk** [comment]
I'm fine with bumping to 5.0 if we've started making these changes, I just didn't think we had done so yet.

**Pull request closed without merging**
