### PR TITLE
Move \r handling from coalescestreams to ANSI filters

### PR DESCRIPTION
**Pull request by mgeier**
See also https://github.com/jupyter/nbconvert/issues/228#issuecomment-183977301.

### CODE REVIEW

**Comment by minrk** [comment]
I'm not sure this is right because it means this now happens in the jinja stage, and won't happen for non-jinja outputs (e.g. `nbconvert --to notebook --execute`), right?

**Comment by mgeier** [comment]
Good point, I wasn't thinking about that!

Ideally, the "execute" preprocessor would use the same code as the live notebook to store the output streams back to the notebook data structure. But I guess it doesn't, right?

**Comment by minrk** [comment]
It doesn't because that's what the coalesce_streams preprocessor already accomplishes. Older versions of the javascript also didn't apply the coalescing, or only applied some, so it should probably still be performed at the preprocessing stage, whether handling is *added* to the ANSI filters or not.

**Comment by mgeier** [comment]
OK, thanks for the explanation!
I see now why the `\r` handling happens in `coalesce_streams`.

I'm closing this ...

**Pull request closed without merging**
