### PR TITLE
ENH: Add SanitizeHTML preprocessor.

### PR DESCRIPTION
**Pull request by ssanderson**
Uses [bleach](https://github.com/jsocol/bleach) as the underlying engine for sanitization.

### CODE REVIEW

**Comment by ssanderson** [comment]
ping @minrk

**Comment by ssanderson** [comment]
(This probably wants unit tests before it's actually merged).

**Comment by minrk** [comment]
Yup, tests would be great.

**Comment by yuvipanda** [comment]
I've rebased this and added more tests at https://github.com/jupyter/nbconvert/pull/172

**Pull request closed without merging**
