### PR TITLE
add help page to docs and update README

### LINKED ISSUE #1376: GitHub Issues not mentioned on website
@willingc FYI, the nbconvert "questions/suggestions" section has 4 links, none of which are to GitHub Issues.
https://nbconvert.readthedocs.io/en/latest/

The Google Group mentioned there doesn't seem to be followed closely.

My understanding from our discussion on Twitter is that GitHub Issues is a (the?) place for questions/suggestions. Therefore it might be good to add this to the above page.

### PR DESCRIPTION
**Pull request by willingc**
Closes #1376

### CODE REVIEW

**Review by t-makaro — APPROVED** [review]

**Comment by willingc** [comment]
Thanks @t-makaro for the review. Once it is green, I will merge. Hope you are doing well.

**Review by choldgraf — APPROVED** [review]
✨✨🚀🚀

**Review by choldgraf — APPROVED** [review]

**Comment by willingc** [comment]
Thanks @choldgraf. I'm thinking that it would be good to move this over to the newer doc style thta we have been using.

**Comment by choldgraf** [comment]
Do you mean MyST? +1 from me obviously :-)

**Comment by willingc** [comment]
@cholgraf Will you open an issue asking folks if there is any technical reason not to do so.

**Comment by choldgraf** [comment]
https://github.com/jupyter/nbconvert/issues/1378

**Pull request merged**
