### PR TITLE
line1 typo in latex/style_ipython.tex.j2

### PR DESCRIPTION
**Pull request by phaustin**

### CODE REVIEW

**Comment by MSeal** [comment]
@maartenbreddels @SylvainCorlay Can you two review this? I'm less familiar with the expectations in tex files than you two are.

**Comment by SylvainCorlay** [comment]
Hum, I really don't know about this. @Carreau may be able to give an educated review.

**Comment by phaustin** [comment]
pretty sure it's just a stray editing error -- without this patch that fragment is injected at the start of the tex file and latex won't run.

**Comment by phaustin** [comment]
Loosely related -- we're working on using paged.js and chrome headless to remove the need for latex (similar to what R is doing with bookdown).  See https://github.com/eoas-ubc/paged_trio/blob/master/Readme.md for some links

**Comment by Carreau** [comment]
Don't remember seeing this file before, but the fix seem good to me. Thanks !

**Pull request merged**
