### PR TITLE
Handle ValueErrors raised by get_exporter

### LINKED ISSUE #1366: Handle missing templates
In unit tests, we typically override the Jupyter [environment variables](https://github.com/jupyterlab/jupyterlab/blob/9c5252392fa671949d67fe5aa2b83c78144e066b/jupyterlab/tests/test_app.py#L108) for isolation.  
We are seeing errors due to missing templates as a result.

- `pip install -U jupyterlab nbconvert`
- `python -m jupyterlab.browser_check`

```python
Traceback (most recent call last):
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/tornado/web.py", line 3178, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/jupyter_server/services/nbconvert/handlers.py", line 17, in get
    exporters = base.get_export_names()
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
    if getattr(exporter(config=config), 'enabled', True):
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 323, in __init__
    super().__init__(config=config, **kw)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 115, in __init__
    self._init_preprocessors()
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 489, in _init_preprocessors
    conf = self._get_conf()
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 505, in _get_conf
    for path in map(Path, self.template_paths):
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/traitlets.py", line 573, in __get__
    return self.get(obj, cls)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/traitlets.py", line 536, in get
    default = obj.trait_defaults(self.name)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/traitlets.py", line 1575, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/traitlets.py", line 973, in __call__
    return self.func(*args, **kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 516, in _template_paths
    template_names = self.get_template_names()
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 577, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'asciidoc' found in the following paths:
	/tmp/tmpcp62hwjq/jupyter_data
	/tmp/tmpcp62hwjq/env/share/jupyter
	/tmp/tmpcp62hwjq/share/jupyter
```

**Nbconvert version:** 6.0.0

### PR DESCRIPTION
**Pull request by blink1073**
Fixes  #1366

```bash
$ python -m jupyterlab.browser_check
...
[I 2020-09-10 06:05:49.817 ServerApp] Test Complete
[I 2020-09-10 06:05:49.817 ServerApp] Exiting normally
[I 2020-09-10 06:05:49.817 ServerApp] Stopping server..
```

### CODE REVIEW

**Comment by blink1073** [comment]
cc @SylvainCorlay ^^

Can you please also add `blink1073` to https://pypi.org/project/nbconvert/?

**Comment by SylvainCorlay** [comment]
> Can you please also add blink1073 to https://pypi.org/project/nbconvert/?

Done.

**Comment by SylvainCorlay** [comment]
@blink1073 merging!

**Comment by SylvainCorlay** [comment]
Do you want to tag 6.0.1 with that patch?

**Comment by blink1073** [comment]
Done!

**Pull request merged**
