### PR TITLE
Change webpdf display name

### PR DESCRIPTION
**Pull request by yuvipanda**
The name has been confusing folks a fair bit. LaTeX
is at least better known.

### CODE REVIEW

**Comment by yuvipanda** [comment]
This shouldn't affect any commandline or API users.

**Comment by yuvipanda** [comment]
An alternative is 'PDF via Chrome' - more accurate, and better brand recognition.

**Review by MSeal — APPROVED** [review]
Thanks for the user feedback. I agree that this name is clearer

**Comment by MSeal** [comment]
Probably means we should do a patch release in the near future -- I have not kept up with the repo over paternity leave though so I have little knowledge of current state of things

**Comment by betatim** [comment]
What is the best way to deal with the fact that https://github.com/betatim/notebook-as-pdf uses the same text as display name? Will users get two entries in their menu and how can they tell the difference?

**Pull request merged**
