### PR TITLE
Doc improver

### PR DESCRIPTION
**Pull request by michaelpacer**
This builds for my repo on rtd. https://readthedocs.org/projects/nbconvert-mp/builds/4469568/

### CODE REVIEW

**Comment by michaelpacer** [comment]
As pointed out by @Carreau, we can't actually release this solution because it will kill the ability to have documentation with branches.

**Comment by michaelpacer** [comment]
with the previous caveat of being unreleasable, this seems to address #439

**Comment by michaelpacer** [comment]
Yay! So on my rtd branch, this most recent version works and it won't be strictly tied to any particular release, but will build it relative to the current version of the file.

I'm guessing that a _lot_ of our issues in the past with rtd have been secretly linked to the fact that we were not building the correct version of nbconvert with which to run the docs by using pip.

Is this the solution used in other places? to include a pip call directly in RTD? 

Also, since I used the `subprocess.run()` command, we need to ensure that the python in the env is at least python 3.5 (which it seems rtd was already doing for me).

**Comment by willingc** [comment]
@michaelpacer I'm going to merge this as the code looks good to me and it's building on your test site. We do use subprocess.run() in the ipywidgets docs build. 

My test on RTD is most grumpy. Probably will just delete it:
screen shot 2016-10-03 at 17 01 17

Overall, let's see how it goes after merging :tada: 🏄

**Pull request merged**
