### PR TITLE
Implement 16 named ANSI colors

### PR DESCRIPTION
**Pull request by mgeier**
... instead of 8. See #245.

For this to work, the notebook CSS has to be updated:

```css
.ansi-black-fg { color: #3E424D; }
.ansi-black-bg { background-color: #3E424D; }
.ansi-black-intense-fg { color: #282C36; }
.ansi-black-intense-bg { background-color: #282C36; }
.ansi-red-fg { color: #E75C58; }
.ansi-red-bg { background-color: #E75C58; }
.ansi-red-intense-fg { color: #B22B31; }
.ansi-red-intense-bg { background-color: #B22B31; }
.ansi-green-fg { color: #00A250; }
.ansi-green-bg { background-color: #00A250; }
.ansi-green-intense-fg { color: #007427; }
.ansi-green-intense-bg { background-color: #007427; }
.ansi-yellow-fg { color: #DDB62B; }
.ansi-yellow-bg { background-color: #DDB62B; }
.ansi-yellow-intense-fg { color: #B27D12; }
.ansi-yellow-intense-bg { background-color: #B27D12; }
.ansi-blue-fg { color: #208FFB; }
.ansi-blue-bg { background-color: #208FFB; }
.ansi-blue-intense-fg { color: #0065CA; }
.ansi-blue-intense-bg { background-color: #0065CA; }
.ansi-magenta-fg { color: #D160C4; }
.ansi-magenta-bg { background-color: #D160C4; }
.ansi-magenta-intense-fg { color: #A03196; }
.ansi-magenta-intense-bg { background-color: #A03196; }
.ansi-cyan-fg { color: #60C6C8; }
.ansi-cyan-bg { background-color: #60C6C8; }
.ansi-cyan-intense-fg { color: #258F8F; }
.ansi-cyan-intense-bg { background-color: #258F8F; }
.ansi-white-fg { color: #C5C1B4; }
.ansi-white-bg { background-color: #C5C1B4; }
.ansi-white-intense-fg { color: #A1A6B2; }
.ansi-white-intense-bg { background-color: #A1A6B2; }

.ansi-bold { font-weight: bold; }
```

I chose the colors as a mix of http://www.xcolors.net/dl/baskerville-ivorylight and http://www.xcolors.net/dl/euphrasia.

I haven't changed the tests yet, I'd like to get some feedback before doing that.

Any comments?

### CODE REVIEW

**Comment by takluyver** [comment]
In that case, it will also need a new release of the notebook, and nbconvert will have to pull in the CSS from that new version. So I guess the notebook is the thing to focus on first.

I have no objection to differentiating the bright versions of colours.

**Comment by Carreau** [comment]
> I have no objection to differentiating the bright versions of colours.

Neither do I.

**Comment by minrk** [comment]
To avoid relying on a notebook release, we can add an additional CSS file to this repo, for any classes needed here that are not (or not yet) defined or available there.

**Comment by mgeier** [comment]
Thanks for the feedback!

I'll try to hack this into the `notebook` in the next few days/weeks, and if successful, I'll come back here afterwards.

**Comment by mgeier** [comment]
I made a PR for the Notebook: https://github.com/jupyter/notebook/pull/1230

**Comment by mgeier** [comment]
OK, https://github.com/jupyter/notebook/pull/1230 has been merged.

I've rebased this PR and added tests (b28f2bfd209c979766e1fc6eb3da4c613c14a29d). I've also added support for the escape codes 90-97 and 100-107 (7b799e0f27c253c551a2a824f113024e0df1365c).

I've *not* added the CSS definitions. Is it foreseeable when the next Notebook CSS release will be?

**Comment by mgeier** [comment]
Another thing: I renamed a few colors in the LaTeX template to make clear that those are ANSI colors, but I don't know if the old color names were used anywhere else in a different context.

* unused in `nbconvert` (but probably used elsewhere?):

  orange, myteal, gray, lightgray (was defined twice before this PR!), mediumgray, inputbackground, outputbackground, traceback

* used in `nbconvert`:

  darkorange (used for `linkcolor`), darkgreen (used for `citecolor`)

* colors which I deleted in this PR:

  red, green, brown, blue (this breaks `urlcolor`!), purple, cyan, (one occurence of) lightgray, darkgray, lightred, lightgreen, lightblue, lightpurple

How should I handle this?

One suggestion that comes to my mind:

1. delete all color definitions mentioned above
1. define only the actually used colors with "semantic" names, i.e. `urlcolor`, `linkcolor`, `citecolor` instead of `blue`, `darkorange`, `darkgreen`, respectively

**Comment by minrk** [comment]
> I've not added the CSS definitions. Is it foreseeable when the next Notebook CSS release will be?

notebook-5.0 will not be very soon, and we should be releasing nbconvert *very* soon (it's frankly overdue for a release by months). So if this should get into a minor release, it has to include a copy of the CSS definitions.

**Comment by mgeier** [comment]
OK, I added the temporary CSS definitions: 692594c191d823714554097c1ec2746593a0055e

I'm still waiting on instructions regarding https://github.com/jupyter/nbconvert/pull/259#issuecomment-201735020.

**Comment by minrk** [comment]
@mgeier sorry for not replying. Semantic names sounds good to me, if you want to add that.

**Comment by mgeier** [comment]
I've added the discussed color definitions and removed the unused colors.
I also rebased this PR for your merging convenience!

**Comment by minrk** [comment]
Great, thanks!

**Comment by mgeier** [comment]
Thanks for merging! I'm looking forward to the new release!

**Comment by KristofferC** [comment]
Sorry if this is the wrong place to ask, but is this supposed to work in notebooks as well?

image

**Comment by takluyver** [comment]
Yes (jupyter/notebook#1230), but it's not yet in a released version.

**Comment by KristofferC** [comment]
Thank you for the reference!

**Comment by mgeier** [comment]
@KristofferC Just a little side note: What you call "Light Red" in your example, will actually become very close to the old "Red". The new "Red" will be brighter, which looks fainter and weaker on a white background. That's the reason why I called the colors 9-16 "intense" instead of "light" or "bright".

**Pull request merged**
