### PR TITLE
Embed widget state in notebook on execute

### PR DESCRIPTION
**Pull request by maartenbreddels**
Rebase of #779 which is a followup of #760

### CODE REVIEW

**Comment by mgeier** [comment]
Will this be available in the next release?

It seems to work fine, I also tried it programmatically with `ExecutePreprocessor` and this also works!

**Comment by maartenbreddels** [comment]
I really hope so!
I guess with this PR we can have clean notebooks in the repo, and RTD will execute and serve the notebooks including the widgets right?

**Comment by maartenbreddels** [comment]
I think this branch is ready for review/merge

**Comment by mgeier** [comment]
Can someone please review this?

**Comment by MSeal** [comment]
Will take a close look this next week and try it out

**Comment by mgeier** [comment]
@MSeal Did you have a chance to have a look?

**Comment by MSeal** [comment]
Not yet. I got busy and then vacation hit. I will prioritize digging into
this when I get back.

**Comment by maartenbreddels** [comment]
Added a flag to disable the storing of the widget state, e.g.:
```
python -m nbconvert ipyvolume.ipynb --execute --stdout --to ipynb --ExecutePreprocessor.store_widget_state=False
```

**Comment by MSeal** [comment]
@maartenbreddels Finally got around to looking at this PR. The code looks good, but I'm struggling to reproduce the UI display despite the metadata being present.

`python -m nbconvert TEST.ipynb --to ipynb --execute`

produces

nbconvert

despite the fact that the metadata is getting populated:

[diff.txt](https://github.com/jupyter/nbconvert/files/2999750/diff.txt)

I tried upgrading jupyter classic, jupyter lab, ipython, etc but I'm not getting the rendering that others were posted in related threads to this PR. Ideas for what might be wrong in my setup to reproduce or what might be going wrong with widget state?

**Comment by maartenbreddels** [comment]
Do you get a rendering if you simply execute the cells in the notebook? If not, there may be an issue with the installation of ipywidgets, for instance pre notebook 5.3 you had to enable the extension manually.

**Comment by MSeal** [comment]
Yes. It renders fine if I execute the cells from classic or lab. I upgraded to latest widgets, ipython, and lab (classic hadn't updated in a while). Maybe I should try some different browser / OS combinations. I am on Ubuntu 17.10 latest Chrome

**Comment by maartenbreddels** [comment]
I had to click File->'Trust this notebook'

**Comment by MSeal** [comment]
Ahh yes, I figured I was missing something silly. Each run of the notebook is requiring me to re-trust the outcome, but that's a separate conversation / thread.

**Comment by maartenbreddels** [comment]
Thanks, and yes indeed, I'd rather see this merged first.

**Comment by maartenbreddels** [comment]
Thanks, really happy to see this in master, looking forward to the next release!

**Comment by MSeal** [comment]
Thanks for making the PRs. I'll try reading through 901 later this week. Plan is currently to do a release early to mid April after some other changes get finalized.

**Comment by MSeal** [comment]
@maartenbreddels Any chance you could add those document requests before we release? It'd help with making the release notes.

**Comment by maartenbreddels** [comment]
I propose the following at the end of execute_api.rst:

```

Widget state
------------

If your notebook contains any `Jupyter Widgets <https://github.com/jupyter-widgets/ipywidgets/>`_,
the state of all the widgets can be stored in the notebook's metadata (starting from nbconvert 5.5).
This allows rendering of the live widgets on for instance nbviewer, or when converting to html.
We can tell nbconvert to not store the state using the `store_widget_state` argument::

    jupyter nbconvert --ExecutePreprocessor.store_widget_state=False --to notebook --execute mynotebook.ipynb

```

Feel free to copy/paste and/or modify if you want (I think it is less work than opening a PR for this, unless you disagree)

**Comment by MSeal** [comment]
I'll probably open a PR anyway so it's more visible -- but that helps. The only additions I think we should include might be:

```
This widget rendering is not performed against a browser during execution, so only widget default states or states manipulated via user code will be calculated during execution. `%%javascript` cells will execute upon notebook rendering, enabling complex interactions to function as expected when viewed by a UI.

If you can't view widget results after execution, you may need to select `Trust Notebook` under the `File` menu.
```

Thoughts or rewording?

**Comment by maartenbreddels** [comment]
sounds good!




Op do 4 apr. 2019 om 19:32 schreef Matthew Seal <notifications@github.com>:

**Pull request merged**
