### PR TITLE
[Accessibility] some accessibility improvements

### PR DESCRIPTION
**Pull request by brichet**
This PR improves the accessibility of the produced HTML file, using the `HTMLExporter`:
- adds a main landmark for the Notebook content
- adds a lang attribute to the `html` tag, configurable with a trait
- adds missing alternative text on images produced by matplotlib
- adds `tabindex="0"` to the inputs and outputs, in order to be able to navigate through the Notebook using the tab key

### CODE REVIEW

**Comment by mgeier** [comment]
I'm not a user of a screenreader, so I might be missing something, but how is `alt="Image"` helping anyone? Doesn't a screenreader already tell you it's an image? Wouldn't it say "image" twice? Assuming the screenreader is even used by an english-speaking user ...

I don't know a solution here, but I would like to point out previous discussions: #1993, https://github.com/matplotlib/matplotlib/pull/21328

**Comment by brichet** [comment]
> I'm not a user of a screenreader, so I might be missing something, but how is `alt="Image"` helping anyone?

Thanks for pointing out some discussions.

I agree that it's not really useful as such.
Nevertheless, it seems that the screenreader needs it, at least the Deque University Axe Devtools complains about it. But for informative image, the alternative text should be informative: https://dequeuniversity.com/rules/axe/4.4/image-alt, which is not the case here.

I don't think we can even tell that it's an image from matplotlib when building HTML, so I don't know neither how we can have any information about the content.
The best solution is to have if fixed from matplotlib.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by krassowski** [comment]
> I agree that it's not really useful as such.
Nevertheless, it seems that the screenreader needs it, at least the Deque University Axe Devtools complains about it.

I don't think that blindly satisfying the automated checks here is the right approach. This will provide a false sense of satisfying the requirements. If a notebook contains images without alt the check should error out.

**Comment by brichet** [comment]
> If a notebook contains images without alt the check should error out.

The problem comes from images generated by Matplotlib (at least), and I don't know if it can be fixed by a user currently.
Maybe we could at least have a more consistent text, something like "No description is provided for this image", and print a warning when the HTML is generated.

**Comment by blink1073** [comment]
I'm cutting the release, we can follow up with further improvements in a bug fix release.

**Pull request merged**
